services:
  mc_java:
    image: itzg/minecraft-server
    labels:
      - "mc.platform=true"
    container_name: mc-java
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      MEMORY: 2G
    volumes:
      - /srv/minecraft/java-data:/data:Z
    restart: unless-stopped
